apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: ohorizons-ms
    newName: crsuradev.azurecr.io/angular-app-v1
    newTag: v0.1.1
