apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - backend-secret.yaml
  - backend-deployment.yaml
  - backend-service.yaml
images:
  - name: ohorizons-ms
    newName: your-acr.azurecr.io/ohorizons-ms
    newTag: latest
  - name: ohorizons-tasks-api
    newName: your-acr.azurecr.io/ohorizons-tasks-api
    newTag: latest
